/*
    0. Drop all exist tables
*/
DROP TABLE IF EXISTS MEMBER;

/*
    1.  Create Member table
*/
CREATE TABLE IF NOT EXISTS MEMBER (
    M_ID        BIGINT        NOT NULL AUTO_INCREMENT UNIQUE,
    EMAIL       VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD    VARCHAR(255) NOT NULL,
    NICKNAME    VARCHAR(255) NOT NULL UNIQUE,
    CREATED_DT  DATETIME      DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DT DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (M_ID)
);